// <auto-generated />
using System;
using GW.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GW.Core.Migrations
{
    [DbContext(typeof(SupervisorContext))]
    partial class SupervisorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GW.Core.Models.Access", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FkUnitId")
                        .HasColumnType("int");

                    b.Property<Guid>("FkUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FkUnitId");

                    b.HasIndex("FkUserId");

                    b.ToTable("Access");
                });

            modelBuilder.Entity("GW.Core.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Charge")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("GW.Core.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FkESPId")
                        .HasColumnType("int");

                    b.Property<int>("FkHoltekId")
                        .HasColumnType("int");

                    b.Property<int>("FkOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("FkSTMId")
                        .HasColumnType("int");

                    b.Property<string>("HardwareVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IMEI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MAC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FkESPId");

                    b.HasIndex("FkHoltekId");

                    b.HasIndex("FkOwnerId");

                    b.HasIndex("FkSTMId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("GW.Core.Models.FOTA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FkESPId")
                        .HasColumnType("int");

                    b.Property<int?>("FkHoltekId")
                        .HasColumnType("int");

                    b.Property<int?>("FkOwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("FkSTMId")
                        .HasColumnType("int");

                    b.Property<string>("HardwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IMEI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MAC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FkESPId");

                    b.HasIndex("FkHoltekId");

                    b.HasIndex("FkOwnerId");

                    b.HasIndex("FkSTMId");

                    b.ToTable("FOTA");
                });

            modelBuilder.Entity("GW.Core.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("FkDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("FkUserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FkDeviceId");

                    b.HasIndex("FkUserRoleId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("GW.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Development"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Production"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Collaborators"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Support"
                        });
                });

            modelBuilder.Entity("GW.Core.Models.SoftwareVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<int>("MicroType")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SoftwareVersions");
                });

            modelBuilder.Entity("GW.Core.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("GW.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3b3c29a-4e2c-4b25-b6f4-2f8ebc4a1f05"),
                            FName = "s",
                            LName = "hasanabadi",
                            Mobile = "09155909973",
                            Password = "$2a$13$IJx6qkqyuUqmuM7NLKZDM.V1SnroBT0ICRHtcaS1AwYkr6z4p1xr6",
                            Username = "sdh"
                        });
                });

            modelBuilder.Entity("GW.Core.Models.UserAndCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FkCompanyId")
                        .HasColumnType("int");

                    b.Property<Guid>("FkUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FkCompanyId");

                    b.HasIndex("FkUserId");

                    b.ToTable("UserAndCompany");
                });

            modelBuilder.Entity("GW.Core.Models.UserRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FkRoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("FkUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FkRoleId");

                    b.HasIndex("FkUserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FkRoleId = 1,
                            FkUserId = new Guid("d3b3c29a-4e2c-4b25-b6f4-2f8ebc4a1f05")
                        });
                });

            modelBuilder.Entity("GW.Core.Models.Access", b =>
                {
                    b.HasOne("GW.Core.Models.Unit", "Unit")
                        .WithMany("Access")
                        .HasForeignKey("FkUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GW.Core.Models.User", "User")
                        .WithMany("Access")
                        .HasForeignKey("FkUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GW.Core.Models.Device", b =>
                {
                    b.HasOne("GW.Core.Models.SoftwareVersion", "ESP")
                        .WithMany("ESPVersions")
                        .HasForeignKey("FkESPId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GW.Core.Models.SoftwareVersion", "Holtek")
                        .WithMany("HoltekVersions")
                        .HasForeignKey("FkHoltekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GW.Core.Models.Company", "ProductOwner")
                        .WithMany("Devices")
                        .HasForeignKey("FkOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GW.Core.Models.SoftwareVersion", "STM")
                        .WithMany("STMVersions")
                        .HasForeignKey("FkSTMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ESP");

                    b.Navigation("Holtek");

                    b.Navigation("ProductOwner");

                    b.Navigation("STM");
                });

            modelBuilder.Entity("GW.Core.Models.FOTA", b =>
                {
                    b.HasOne("GW.Core.Models.SoftwareVersion", "ESP")
                        .WithMany("FOTAESPVersions")
                        .HasForeignKey("FkESPId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GW.Core.Models.SoftwareVersion", "Holtek")
                        .WithMany("FOTAHoltekVersions")
                        .HasForeignKey("FkHoltekId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GW.Core.Models.Company", "ProductOwner")
                        .WithMany("FOTAs")
                        .HasForeignKey("FkOwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GW.Core.Models.SoftwareVersion", "STM")
                        .WithMany("FOTASTMVersions")
                        .HasForeignKey("FkSTMId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ESP");

                    b.Navigation("Holtek");

                    b.Navigation("ProductOwner");

                    b.Navigation("STM");
                });

            modelBuilder.Entity("GW.Core.Models.Log", b =>
                {
                    b.HasOne("GW.Core.Models.Device", "Device")
                        .WithMany("Logs")
                        .HasForeignKey("FkDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GW.Core.Models.UserRoles", "UserRole")
                        .WithMany("Logs")
                        .HasForeignKey("FkUserRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("GW.Core.Models.UserAndCompany", b =>
                {
                    b.HasOne("GW.Core.Models.Company", "Company")
                        .WithMany("UserAndCompanies")
                        .HasForeignKey("FkCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GW.Core.Models.User", "User")
                        .WithMany("UserAndCompanies")
                        .HasForeignKey("FkUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GW.Core.Models.UserRoles", b =>
                {
                    b.HasOne("GW.Core.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("FkRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GW.Core.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("FkUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GW.Core.Models.Company", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("FOTAs");

                    b.Navigation("UserAndCompanies");
                });

            modelBuilder.Entity("GW.Core.Models.Device", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("GW.Core.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GW.Core.Models.SoftwareVersion", b =>
                {
                    b.Navigation("ESPVersions");

                    b.Navigation("FOTAESPVersions");

                    b.Navigation("FOTAHoltekVersions");

                    b.Navigation("FOTASTMVersions");

                    b.Navigation("HoltekVersions");

                    b.Navigation("STMVersions");
                });

            modelBuilder.Entity("GW.Core.Models.Unit", b =>
                {
                    b.Navigation("Access");
                });

            modelBuilder.Entity("GW.Core.Models.User", b =>
                {
                    b.Navigation("Access");

                    b.Navigation("UserAndCompanies");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GW.Core.Models.UserRoles", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
